[[headers]]
  for = "/*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=2260000"

[[headers]]
  for = "/*.png"
  [headers.values]
    Cache-Control = "public, max-age=2260000"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=2260000"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=2260000"

[[headers]]
  for = "/*.webp"
  [headers.values]
    Cache-Control = "public, max-age=2260000"

[build]
  environment = { NODE_OPTIONS = "--max_old_space_size=4096", NODE_VERSION = "20.11.1" }
